version: '3.8'

services:
  psychic-signatures:
    build: .
    container_name: psychic_signatures_ctf
    ports:
      - "6001:6001"
    volumes:
      - .:/app
    working_dir: /app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
