version: '3.8'

services:
  psychic-signatures:
    build: .
    container_name: psychic_signatures_ctf
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1  # Enable debug mode for detailed logging
      FLASK_RUN_HOST: 0.0.0.0  # Run Flask on all available interfaces
      FLASK_RUN_PORT: 5000  # Explicitly set Flask's port
