version: "3.8"
services:
  client_side_exploit:
    build: .
    container_name: client_side_exploit
    ports:
      - "5000:5000"
    volumes:
      - ./flags:/app/flags
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    restart: unless-stopped