version: '3'
services:
  oracle-web:
    build: ./oracle-web
    ports:
      - "8080:5000"
    depends_on:
      - internal-api

  internal-api:
    build: ./internal-api
    ports:
      - "6008:8000"  # 👈 så oraklet når mål via http://127.0.0.1:6008
